spring:
  port: 8080
  main:
    banner-mode: console
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  frontend:
    urls: ${FRONTEND_URLS:http://localhost:3000,https://rishabh-147.github.io}

music:
  folder: ${MUSIC_FOLDER:C:/Users/tiwar/Music/Audio}