spring:
  port: 8081
  main:
    banner-mode: console
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

app:
  frontend:
    url: http://localhost:3000

music:
  folder: ${MUSIC_FOLDER:C:/Users/tiwar/Music/Audio}